# Generated by Django 5.1.5 on 2025-02-14 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study_hub", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursematerial",
            name="file",
            field=models.FileField(upload_to="media/course_materials/"),
        ),
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/profile_photos/"
            ),
        ),
    ]
