# Generated by Django 5.1.5 on 2025-02-09 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("study_hub", "0002_alter_user_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="study_hub.course"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="study_hub_user_set",
                related_query_name="user",
                to="auth.group",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="study_hub_user_set",
                related_query_name="user",
                to="auth.permission",
            ),
        ),
    ]
